### ISSUE TITLE
Rebuild container 

### ISSUE THREAD

**Issue by Pashtetickus** [edvardpotter/outline-web-manager#2]
Hello.

I installed the application, tried to change the admin email - deleted it and created another one. After that, when trying to log in with default admin email and password, the error `"Invalid credentials"` pops up. I tried to rebuild the container, but the error remained. I added a new user using the following command: 
`docker exec outline-web-manager-php-1 bin/console user:create email passwd`. 
After doing this, I have logged in. In users I see id 3, but I can't figure out where all the previous users are.

![image](https://github.com/edvardpotter/outline-web-manager/assets/46760758/b298b834-8c0d-49b5-9af2-5d5d21a23bcc)

So the question is: how to purge all docker cache (or app cache) and build clean container again? It looks like some auth data stored in host DB, but i don't know how to find it and clear.

I tried also this (didn't help):
```
docker-compose build --no-cache --pull
docker-compose up -d --force-recreate
```

And this also didn't help:
```
docker builder prune --all
docker system prune
```

So i solved it like this, but i don't completely understand why and how this db caching, while rebuilding container:
```
docker exec outline-web-manager-php-1 bin/console doctrine:database:drop --force
docker exec outline-web-manager-php-1 bin/console doctrine:database:create
docker exec outline-web-manager-php-1 bin/console doctrine:migrations:migrate
docker exec outline-web-manager-php-1 bin/console assets:install
docker exec outline-web-manager-php-1 bin/console user:create user@email.local 123456
```

**Comment by edvardpotter** [comment]
Hi @Pashtetickus!
I didn’t quite understand what your problem is, you created a new user, you can log in with his credentials to the admin panel, and also see him in the list of users. The rest of the accounts, if I understand correctly, you deleted and therefore they are not displayed.

Regarding caching information and clearing the database, all data is stored in sqlite, the file is located on the path var/data.db. If you want to rebuild the container, you also need to remove the docker volume (`docker volume rm outline-manager-web_php_public`) since all files are stored in it.

**Comment by Pashtetickus** [comment]
Now i see. It seems i was looking where this volume is. Thank you.
